// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: touchFreeAtm.proto

package com.bron.grpc;

public interface authenticationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authenticationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isCorrectPin = 1;</code>
   */
  boolean getIsCorrectPin();

  /**
   * <code>string welcomeMessage = 2;</code>
   */
  java.lang.String getWelcomeMessage();
  /**
   * <code>string welcomeMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getWelcomeMessageBytes();
}
