// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: touchFreeAtm.proto

package com.bron.grpc;

/**
 * <pre>
 *rpc 1: authenticateCard
 * </pre>
 *
 * Protobuf type {@code authenticationMessage}
 */
public  final class authenticationMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:authenticationMessage)
    authenticationMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use authenticationMessage.newBuilder() to construct.
  private authenticationMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private authenticationMessage() {
    isCorrectPin_ = false;
    welcomeMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private authenticationMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            isCorrectPin_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            welcomeMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bron.grpc.TouchFreeAtm.internal_static_authenticationMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bron.grpc.TouchFreeAtm.internal_static_authenticationMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bron.grpc.authenticationMessage.class, com.bron.grpc.authenticationMessage.Builder.class);
  }

  public static final int ISCORRECTPIN_FIELD_NUMBER = 1;
  private boolean isCorrectPin_;
  /**
   * <code>bool isCorrectPin = 1;</code>
   */
  public boolean getIsCorrectPin() {
    return isCorrectPin_;
  }

  public static final int WELCOMEMESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object welcomeMessage_;
  /**
   * <code>string welcomeMessage = 2;</code>
   */
  public java.lang.String getWelcomeMessage() {
    java.lang.Object ref = welcomeMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      welcomeMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string welcomeMessage = 2;</code>
   */
  public com.google.protobuf.ByteString
      getWelcomeMessageBytes() {
    java.lang.Object ref = welcomeMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      welcomeMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isCorrectPin_ != false) {
      output.writeBool(1, isCorrectPin_);
    }
    if (!getWelcomeMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, welcomeMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isCorrectPin_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isCorrectPin_);
    }
    if (!getWelcomeMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, welcomeMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bron.grpc.authenticationMessage)) {
      return super.equals(obj);
    }
    com.bron.grpc.authenticationMessage other = (com.bron.grpc.authenticationMessage) obj;

    boolean result = true;
    result = result && (getIsCorrectPin()
        == other.getIsCorrectPin());
    result = result && getWelcomeMessage()
        .equals(other.getWelcomeMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISCORRECTPIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCorrectPin());
    hash = (37 * hash) + WELCOMEMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getWelcomeMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bron.grpc.authenticationMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.authenticationMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.authenticationMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.authenticationMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.authenticationMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.authenticationMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.authenticationMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bron.grpc.authenticationMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bron.grpc.authenticationMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bron.grpc.authenticationMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bron.grpc.authenticationMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bron.grpc.authenticationMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bron.grpc.authenticationMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *rpc 1: authenticateCard
   * </pre>
   *
   * Protobuf type {@code authenticationMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:authenticationMessage)
      com.bron.grpc.authenticationMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bron.grpc.TouchFreeAtm.internal_static_authenticationMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bron.grpc.TouchFreeAtm.internal_static_authenticationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bron.grpc.authenticationMessage.class, com.bron.grpc.authenticationMessage.Builder.class);
    }

    // Construct using com.bron.grpc.authenticationMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isCorrectPin_ = false;

      welcomeMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bron.grpc.TouchFreeAtm.internal_static_authenticationMessage_descriptor;
    }

    @java.lang.Override
    public com.bron.grpc.authenticationMessage getDefaultInstanceForType() {
      return com.bron.grpc.authenticationMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.bron.grpc.authenticationMessage build() {
      com.bron.grpc.authenticationMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bron.grpc.authenticationMessage buildPartial() {
      com.bron.grpc.authenticationMessage result = new com.bron.grpc.authenticationMessage(this);
      result.isCorrectPin_ = isCorrectPin_;
      result.welcomeMessage_ = welcomeMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bron.grpc.authenticationMessage) {
        return mergeFrom((com.bron.grpc.authenticationMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bron.grpc.authenticationMessage other) {
      if (other == com.bron.grpc.authenticationMessage.getDefaultInstance()) return this;
      if (other.getIsCorrectPin() != false) {
        setIsCorrectPin(other.getIsCorrectPin());
      }
      if (!other.getWelcomeMessage().isEmpty()) {
        welcomeMessage_ = other.welcomeMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bron.grpc.authenticationMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bron.grpc.authenticationMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isCorrectPin_ ;
    /**
     * <code>bool isCorrectPin = 1;</code>
     */
    public boolean getIsCorrectPin() {
      return isCorrectPin_;
    }
    /**
     * <code>bool isCorrectPin = 1;</code>
     */
    public Builder setIsCorrectPin(boolean value) {
      
      isCorrectPin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isCorrectPin = 1;</code>
     */
    public Builder clearIsCorrectPin() {
      
      isCorrectPin_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object welcomeMessage_ = "";
    /**
     * <code>string welcomeMessage = 2;</code>
     */
    public java.lang.String getWelcomeMessage() {
      java.lang.Object ref = welcomeMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        welcomeMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string welcomeMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWelcomeMessageBytes() {
      java.lang.Object ref = welcomeMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        welcomeMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string welcomeMessage = 2;</code>
     */
    public Builder setWelcomeMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      welcomeMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string welcomeMessage = 2;</code>
     */
    public Builder clearWelcomeMessage() {
      
      welcomeMessage_ = getDefaultInstance().getWelcomeMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string welcomeMessage = 2;</code>
     */
    public Builder setWelcomeMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      welcomeMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:authenticationMessage)
  }

  // @@protoc_insertion_point(class_scope:authenticationMessage)
  private static final com.bron.grpc.authenticationMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bron.grpc.authenticationMessage();
  }

  public static com.bron.grpc.authenticationMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<authenticationMessage>
      PARSER = new com.google.protobuf.AbstractParser<authenticationMessage>() {
    @java.lang.Override
    public authenticationMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new authenticationMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<authenticationMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<authenticationMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bron.grpc.authenticationMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

