// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: touchFreeAtm.proto

package com.bron.grpc;

public interface availableMachinesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:availableMachines)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Machine = 1;</code>
   */
  java.lang.String getMachine();
  /**
   * <code>string Machine = 1;</code>
   */
  com.google.protobuf.ByteString
      getMachineBytes();

  /**
   * <code>float distance = 2;</code>
   */
  float getDistance();
}
