// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

public final class BudgetApp {
  private BudgetApp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moneySpent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moneySpent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lowBudgetAlert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lowBudgetAlert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_requestRemainingbudget_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_requestRemainingbudget_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_remainingBudgetStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_remainingBudgetStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_updatedBudget_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_updatedBudget_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_updatedBudgetConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_updatedBudgetConfirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_setBudget_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_setBudget_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017budgetApp.proto\"0\n\nmoneySpent\022\024\n\014catag" +
      "oryName\030\001 \001(\t\022\014\n\004cost\030\002 \001(\001\",\n\016lowBudget" +
      "Alert\022\032\n\022nearingBudgetAlert\030\001 \001(\t\"8\n\026req" +
      "uestRemainingbudget\022\036\n\026requestRemainingb" +
      "udget\030\001 \001(\010\"4\n\025remainingBudgetStream\022\016\n\006" +
      "Budget\030\001 \001(\001\022\013\n\003Cat\030\002 \001(\t\">\n\rupdatedBudg" +
      "et\022\026\n\016youHaveUpdated\030\001 \001(\t\022\025\n\rupdatedBud" +
      "get\030\002 \001(\005\"(\n\031updatedBudgetConfirmation\022\013" +
      "\n\003Cat\030\001 \001(\t\"8\n\tsetBudget\022\023\n\013OriginalCat\030" +
      "\001 \001(\t\022\026\n\016OriginalBudget\030\002 \001(\0012\362\001\n\006Budget" +
      "\0222\n\020getBudgetWarning\022\013.moneySpent\032\017.lowB" +
      "udgetAlert\"\000\022I\n\022getRemainingBudget\022\027.req" +
      "uestRemainingbudget\032\026.remainingBudgetStr" +
      "eam\"\0000\001\022>\n\014updateBugdet\022\016.updatedBudget\032" +
      "\032.updatedBudgetConfirmation\"\000(\001\022)\n\tSetBu" +
      "dget\022\n.setBudget\032\n.setBudget\"\000(\0010\001B\021\n\rco" +
      "m.bron.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_moneySpent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_moneySpent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moneySpent_descriptor,
        new java.lang.String[] { "CatagoryName", "Cost", });
    internal_static_lowBudgetAlert_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lowBudgetAlert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lowBudgetAlert_descriptor,
        new java.lang.String[] { "NearingBudgetAlert", });
    internal_static_requestRemainingbudget_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_requestRemainingbudget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_requestRemainingbudget_descriptor,
        new java.lang.String[] { "RequestRemainingbudget", });
    internal_static_remainingBudgetStream_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_remainingBudgetStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_remainingBudgetStream_descriptor,
        new java.lang.String[] { "Budget", "Cat", });
    internal_static_updatedBudget_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_updatedBudget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_updatedBudget_descriptor,
        new java.lang.String[] { "YouHaveUpdated", "UpdatedBudget", });
    internal_static_updatedBudgetConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_updatedBudgetConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_updatedBudgetConfirmation_descriptor,
        new java.lang.String[] { "Cat", });
    internal_static_setBudget_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_setBudget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_setBudget_descriptor,
        new java.lang.String[] { "OriginalCat", "OriginalBudget", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
