// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: touchFreeAtm.proto

package com.bron.grpc;

public interface inputPinOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inputPin)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pinNumber = 1;</code>
   */
  int getPinNumber();
}
