// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

public interface lowBudgetAlertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lowBudgetAlert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nearingBudgetAlert = 1;</code>
   */
  java.lang.String getNearingBudgetAlert();
  /**
   * <code>string nearingBudgetAlert = 1;</code>
   */
  com.google.protobuf.ByteString
      getNearingBudgetAlertBytes();
}
