// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

public interface moneySpentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moneySpent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string catagoryName = 1;</code>
   */
  java.lang.String getCatagoryName();
  /**
   * <code>string catagoryName = 1;</code>
   */
  com.google.protobuf.ByteString
      getCatagoryNameBytes();

  /**
   * <code>double cost = 2;</code>
   */
  double getCost();
}
