// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

public interface remainingBudgetStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remainingBudgetStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double Budget = 1;</code>
   */
  double getBudget();

  /**
   * <code>string Cat = 2;</code>
   */
  java.lang.String getCat();
  /**
   * <code>string Cat = 2;</code>
   */
  com.google.protobuf.ByteString
      getCatBytes();
}
