// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

public interface requestRemainingbudgetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:requestRemainingbudget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool requestRemainingbudget = 1;</code>
   */
  boolean getRequestRemainingbudget();
}
