// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

/**
 * Protobuf type {@code requestRemainingbudget}
 */
public  final class requestRemainingbudget extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:requestRemainingbudget)
    requestRemainingbudgetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use requestRemainingbudget.newBuilder() to construct.
  private requestRemainingbudget(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private requestRemainingbudget() {
    requestRemainingbudget_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private requestRemainingbudget(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            requestRemainingbudget_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bron.grpc.BudgetApp.internal_static_requestRemainingbudget_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bron.grpc.BudgetApp.internal_static_requestRemainingbudget_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bron.grpc.requestRemainingbudget.class, com.bron.grpc.requestRemainingbudget.Builder.class);
  }

  public static final int REQUESTREMAININGBUDGET_FIELD_NUMBER = 1;
  private boolean requestRemainingbudget_;
  /**
   * <code>bool requestRemainingbudget = 1;</code>
   */
  public boolean getRequestRemainingbudget() {
    return requestRemainingbudget_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestRemainingbudget_ != false) {
      output.writeBool(1, requestRemainingbudget_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestRemainingbudget_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, requestRemainingbudget_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bron.grpc.requestRemainingbudget)) {
      return super.equals(obj);
    }
    com.bron.grpc.requestRemainingbudget other = (com.bron.grpc.requestRemainingbudget) obj;

    boolean result = true;
    result = result && (getRequestRemainingbudget()
        == other.getRequestRemainingbudget());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUESTREMAININGBUDGET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRequestRemainingbudget());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bron.grpc.requestRemainingbudget parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.requestRemainingbudget parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.requestRemainingbudget parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.requestRemainingbudget parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.requestRemainingbudget parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.requestRemainingbudget parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.requestRemainingbudget parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bron.grpc.requestRemainingbudget parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bron.grpc.requestRemainingbudget parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bron.grpc.requestRemainingbudget parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bron.grpc.requestRemainingbudget parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bron.grpc.requestRemainingbudget parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bron.grpc.requestRemainingbudget prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code requestRemainingbudget}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:requestRemainingbudget)
      com.bron.grpc.requestRemainingbudgetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bron.grpc.BudgetApp.internal_static_requestRemainingbudget_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bron.grpc.BudgetApp.internal_static_requestRemainingbudget_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bron.grpc.requestRemainingbudget.class, com.bron.grpc.requestRemainingbudget.Builder.class);
    }

    // Construct using com.bron.grpc.requestRemainingbudget.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestRemainingbudget_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bron.grpc.BudgetApp.internal_static_requestRemainingbudget_descriptor;
    }

    @java.lang.Override
    public com.bron.grpc.requestRemainingbudget getDefaultInstanceForType() {
      return com.bron.grpc.requestRemainingbudget.getDefaultInstance();
    }

    @java.lang.Override
    public com.bron.grpc.requestRemainingbudget build() {
      com.bron.grpc.requestRemainingbudget result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bron.grpc.requestRemainingbudget buildPartial() {
      com.bron.grpc.requestRemainingbudget result = new com.bron.grpc.requestRemainingbudget(this);
      result.requestRemainingbudget_ = requestRemainingbudget_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bron.grpc.requestRemainingbudget) {
        return mergeFrom((com.bron.grpc.requestRemainingbudget)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bron.grpc.requestRemainingbudget other) {
      if (other == com.bron.grpc.requestRemainingbudget.getDefaultInstance()) return this;
      if (other.getRequestRemainingbudget() != false) {
        setRequestRemainingbudget(other.getRequestRemainingbudget());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bron.grpc.requestRemainingbudget parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bron.grpc.requestRemainingbudget) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean requestRemainingbudget_ ;
    /**
     * <code>bool requestRemainingbudget = 1;</code>
     */
    public boolean getRequestRemainingbudget() {
      return requestRemainingbudget_;
    }
    /**
     * <code>bool requestRemainingbudget = 1;</code>
     */
    public Builder setRequestRemainingbudget(boolean value) {
      
      requestRemainingbudget_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool requestRemainingbudget = 1;</code>
     */
    public Builder clearRequestRemainingbudget() {
      
      requestRemainingbudget_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:requestRemainingbudget)
  }

  // @@protoc_insertion_point(class_scope:requestRemainingbudget)
  private static final com.bron.grpc.requestRemainingbudget DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bron.grpc.requestRemainingbudget();
  }

  public static com.bron.grpc.requestRemainingbudget getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<requestRemainingbudget>
      PARSER = new com.google.protobuf.AbstractParser<requestRemainingbudget>() {
    @java.lang.Override
    public requestRemainingbudget parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new requestRemainingbudget(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<requestRemainingbudget> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<requestRemainingbudget> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bron.grpc.requestRemainingbudget getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

