// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: touchFreeAtm.proto

package com.bron.grpc;

public interface searchATMOrBuilder extends
    // @@protoc_insertion_point(interface_extends:searchATM)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool searchATM = 1;</code>
   */
  boolean getSearchATM();
}
