// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

public interface setBudgetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:setBudget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string OriginalCat = 1;</code>
   */
  java.lang.String getOriginalCat();
  /**
   * <code>string OriginalCat = 1;</code>
   */
  com.google.protobuf.ByteString
      getOriginalCatBytes();

  /**
   * <code>double OriginalBudget = 2;</code>
   */
  double getOriginalBudget();
}
