// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

/**
 * <pre>
 *rpc 4: setBugdet
 * </pre>
 *
 * Protobuf type {@code setBudget}
 */
public  final class setBudget extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:setBudget)
    setBudgetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use setBudget.newBuilder() to construct.
  private setBudget(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private setBudget() {
    originalCat_ = "";
    originalBudget_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private setBudget(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            originalCat_ = s;
            break;
          }
          case 17: {

            originalBudget_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bron.grpc.BudgetApp.internal_static_setBudget_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bron.grpc.BudgetApp.internal_static_setBudget_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bron.grpc.setBudget.class, com.bron.grpc.setBudget.Builder.class);
  }

  public static final int ORIGINALCAT_FIELD_NUMBER = 1;
  private volatile java.lang.Object originalCat_;
  /**
   * <code>string OriginalCat = 1;</code>
   */
  public java.lang.String getOriginalCat() {
    java.lang.Object ref = originalCat_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      originalCat_ = s;
      return s;
    }
  }
  /**
   * <code>string OriginalCat = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOriginalCatBytes() {
    java.lang.Object ref = originalCat_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originalCat_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINALBUDGET_FIELD_NUMBER = 2;
  private double originalBudget_;
  /**
   * <code>double OriginalBudget = 2;</code>
   */
  public double getOriginalBudget() {
    return originalBudget_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOriginalCatBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, originalCat_);
    }
    if (originalBudget_ != 0D) {
      output.writeDouble(2, originalBudget_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOriginalCatBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, originalCat_);
    }
    if (originalBudget_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, originalBudget_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bron.grpc.setBudget)) {
      return super.equals(obj);
    }
    com.bron.grpc.setBudget other = (com.bron.grpc.setBudget) obj;

    boolean result = true;
    result = result && getOriginalCat()
        .equals(other.getOriginalCat());
    result = result && (
        java.lang.Double.doubleToLongBits(getOriginalBudget())
        == java.lang.Double.doubleToLongBits(
            other.getOriginalBudget()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORIGINALCAT_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalCat().hashCode();
    hash = (37 * hash) + ORIGINALBUDGET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getOriginalBudget()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bron.grpc.setBudget parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.setBudget parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.setBudget parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.setBudget parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.setBudget parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.setBudget parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.setBudget parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bron.grpc.setBudget parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bron.grpc.setBudget parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bron.grpc.setBudget parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bron.grpc.setBudget parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bron.grpc.setBudget parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bron.grpc.setBudget prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *rpc 4: setBugdet
   * </pre>
   *
   * Protobuf type {@code setBudget}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:setBudget)
      com.bron.grpc.setBudgetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bron.grpc.BudgetApp.internal_static_setBudget_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bron.grpc.BudgetApp.internal_static_setBudget_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bron.grpc.setBudget.class, com.bron.grpc.setBudget.Builder.class);
    }

    // Construct using com.bron.grpc.setBudget.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      originalCat_ = "";

      originalBudget_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bron.grpc.BudgetApp.internal_static_setBudget_descriptor;
    }

    @java.lang.Override
    public com.bron.grpc.setBudget getDefaultInstanceForType() {
      return com.bron.grpc.setBudget.getDefaultInstance();
    }

    @java.lang.Override
    public com.bron.grpc.setBudget build() {
      com.bron.grpc.setBudget result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bron.grpc.setBudget buildPartial() {
      com.bron.grpc.setBudget result = new com.bron.grpc.setBudget(this);
      result.originalCat_ = originalCat_;
      result.originalBudget_ = originalBudget_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bron.grpc.setBudget) {
        return mergeFrom((com.bron.grpc.setBudget)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bron.grpc.setBudget other) {
      if (other == com.bron.grpc.setBudget.getDefaultInstance()) return this;
      if (!other.getOriginalCat().isEmpty()) {
        originalCat_ = other.originalCat_;
        onChanged();
      }
      if (other.getOriginalBudget() != 0D) {
        setOriginalBudget(other.getOriginalBudget());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bron.grpc.setBudget parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bron.grpc.setBudget) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object originalCat_ = "";
    /**
     * <code>string OriginalCat = 1;</code>
     */
    public java.lang.String getOriginalCat() {
      java.lang.Object ref = originalCat_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalCat_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string OriginalCat = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOriginalCatBytes() {
      java.lang.Object ref = originalCat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalCat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string OriginalCat = 1;</code>
     */
    public Builder setOriginalCat(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      originalCat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string OriginalCat = 1;</code>
     */
    public Builder clearOriginalCat() {
      
      originalCat_ = getDefaultInstance().getOriginalCat();
      onChanged();
      return this;
    }
    /**
     * <code>string OriginalCat = 1;</code>
     */
    public Builder setOriginalCatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      originalCat_ = value;
      onChanged();
      return this;
    }

    private double originalBudget_ ;
    /**
     * <code>double OriginalBudget = 2;</code>
     */
    public double getOriginalBudget() {
      return originalBudget_;
    }
    /**
     * <code>double OriginalBudget = 2;</code>
     */
    public Builder setOriginalBudget(double value) {
      
      originalBudget_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double OriginalBudget = 2;</code>
     */
    public Builder clearOriginalBudget() {
      
      originalBudget_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:setBudget)
  }

  // @@protoc_insertion_point(class_scope:setBudget)
  private static final com.bron.grpc.setBudget DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bron.grpc.setBudget();
  }

  public static com.bron.grpc.setBudget getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<setBudget>
      PARSER = new com.google.protobuf.AbstractParser<setBudget>() {
    @java.lang.Override
    public setBudget parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new setBudget(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<setBudget> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<setBudget> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bron.grpc.setBudget getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

