// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: touchFreeAtm.proto

package com.bron.grpc;

public final class TouchFreeAtm {
  private TouchFreeAtm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authenticationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authenticationMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inputPin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inputPin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022touchFreeAtm.proto\"E\n\025authenticationMe" +
      "ssage\022\024\n\014isCorrectPin\030\001 \001(\010\022\026\n\016welcomeMe" +
      "ssage\030\002 \001(\t\"\035\n\010inputPin\022\021\n\tpinNumber\030\001 \001" +
      "(\0052G\n\014touchFreeATM\0227\n\020authenticateCard\022\t" +
      ".inputPin\032\026.authenticationMessage\"\000B\021\n\rc" +
      "om.bron.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_authenticationMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authenticationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authenticationMessage_descriptor,
        new java.lang.String[] { "IsCorrectPin", "WelcomeMessage", });
    internal_static_inputPin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inputPin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inputPin_descriptor,
        new java.lang.String[] { "PinNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
