// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: touchFreeAtm.proto

package com.bron.grpc;

public final class TouchFreeAtm {
  private TouchFreeAtm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authenticationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authenticationMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inputPin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inputPin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_searchATM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_searchATM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_availableMachines_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_availableMachines_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022touchFreeAtm.proto\"E\n\025authenticationMe" +
      "ssage\022\024\n\014isCorrectPin\030\001 \001(\010\022\026\n\016welcomeMe" +
      "ssage\030\002 \001(\t\"\035\n\010inputPin\022\021\n\tpinNumber\030\001 \001" +
      "(\005\"\036\n\tsearchATM\022\021\n\tsearchATM\030\001 \001(\010\"6\n\021av" +
      "ailableMachines\022\017\n\007Machine\030\001 \001(\t\022\020\n\010dist" +
      "ance\030\002 \001(\0022|\n\014touchFreeATM\0227\n\020authentica" +
      "teCard\022\t.inputPin\032\026.authenticationMessag" +
      "e\"\000\0223\n\rfindNearByATM\022\n.searchATM\032\022.avail" +
      "ableMachines\"\0000\001B\021\n\rcom.bron.grpcP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_authenticationMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authenticationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authenticationMessage_descriptor,
        new java.lang.String[] { "IsCorrectPin", "WelcomeMessage", });
    internal_static_inputPin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inputPin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inputPin_descriptor,
        new java.lang.String[] { "PinNumber", });
    internal_static_searchATM_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_searchATM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_searchATM_descriptor,
        new java.lang.String[] { "SearchATM", });
    internal_static_availableMachines_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_availableMachines_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_availableMachines_descriptor,
        new java.lang.String[] { "Machine", "Distance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
