// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

public interface updatedBudgetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:updatedBudget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string youHaveUpdated = 1;</code>
   */
  java.lang.String getYouHaveUpdated();
  /**
   * <code>string youHaveUpdated = 1;</code>
   */
  com.google.protobuf.ByteString
      getYouHaveUpdatedBytes();

  /**
   * <code>int32 updatedBudget = 2;</code>
   */
  int getUpdatedBudget();
}
