// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

public interface updatedBudgetConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:updatedBudgetConfirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Cat = 1;</code>
   */
  java.lang.String getCat();
  /**
   * <code>string Cat = 1;</code>
   */
  com.google.protobuf.ByteString
      getCatBytes();
}
