// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: budgetApp.proto

package com.bron.grpc;

/**
 * <pre>
 *rpc 3: updateBugdet
 * </pre>
 *
 * Protobuf type {@code updatedBudget}
 */
public  final class updatedBudget extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:updatedBudget)
    updatedBudgetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use updatedBudget.newBuilder() to construct.
  private updatedBudget(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private updatedBudget() {
    youHaveUpdated_ = "";
    updatedBudget_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private updatedBudget(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            youHaveUpdated_ = s;
            break;
          }
          case 16: {

            updatedBudget_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bron.grpc.BudgetApp.internal_static_updatedBudget_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bron.grpc.BudgetApp.internal_static_updatedBudget_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bron.grpc.updatedBudget.class, com.bron.grpc.updatedBudget.Builder.class);
  }

  public static final int YOUHAVEUPDATED_FIELD_NUMBER = 1;
  private volatile java.lang.Object youHaveUpdated_;
  /**
   * <code>string youHaveUpdated = 1;</code>
   */
  public java.lang.String getYouHaveUpdated() {
    java.lang.Object ref = youHaveUpdated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      youHaveUpdated_ = s;
      return s;
    }
  }
  /**
   * <code>string youHaveUpdated = 1;</code>
   */
  public com.google.protobuf.ByteString
      getYouHaveUpdatedBytes() {
    java.lang.Object ref = youHaveUpdated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      youHaveUpdated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATEDBUDGET_FIELD_NUMBER = 2;
  private int updatedBudget_;
  /**
   * <code>int32 updatedBudget = 2;</code>
   */
  public int getUpdatedBudget() {
    return updatedBudget_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getYouHaveUpdatedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, youHaveUpdated_);
    }
    if (updatedBudget_ != 0) {
      output.writeInt32(2, updatedBudget_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getYouHaveUpdatedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, youHaveUpdated_);
    }
    if (updatedBudget_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, updatedBudget_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bron.grpc.updatedBudget)) {
      return super.equals(obj);
    }
    com.bron.grpc.updatedBudget other = (com.bron.grpc.updatedBudget) obj;

    boolean result = true;
    result = result && getYouHaveUpdated()
        .equals(other.getYouHaveUpdated());
    result = result && (getUpdatedBudget()
        == other.getUpdatedBudget());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + YOUHAVEUPDATED_FIELD_NUMBER;
    hash = (53 * hash) + getYouHaveUpdated().hashCode();
    hash = (37 * hash) + UPDATEDBUDGET_FIELD_NUMBER;
    hash = (53 * hash) + getUpdatedBudget();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bron.grpc.updatedBudget parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.updatedBudget parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.updatedBudget parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.updatedBudget parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.updatedBudget parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bron.grpc.updatedBudget parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bron.grpc.updatedBudget parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bron.grpc.updatedBudget parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bron.grpc.updatedBudget parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bron.grpc.updatedBudget parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bron.grpc.updatedBudget parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bron.grpc.updatedBudget parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bron.grpc.updatedBudget prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *rpc 3: updateBugdet
   * </pre>
   *
   * Protobuf type {@code updatedBudget}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:updatedBudget)
      com.bron.grpc.updatedBudgetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bron.grpc.BudgetApp.internal_static_updatedBudget_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bron.grpc.BudgetApp.internal_static_updatedBudget_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bron.grpc.updatedBudget.class, com.bron.grpc.updatedBudget.Builder.class);
    }

    // Construct using com.bron.grpc.updatedBudget.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      youHaveUpdated_ = "";

      updatedBudget_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bron.grpc.BudgetApp.internal_static_updatedBudget_descriptor;
    }

    @java.lang.Override
    public com.bron.grpc.updatedBudget getDefaultInstanceForType() {
      return com.bron.grpc.updatedBudget.getDefaultInstance();
    }

    @java.lang.Override
    public com.bron.grpc.updatedBudget build() {
      com.bron.grpc.updatedBudget result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bron.grpc.updatedBudget buildPartial() {
      com.bron.grpc.updatedBudget result = new com.bron.grpc.updatedBudget(this);
      result.youHaveUpdated_ = youHaveUpdated_;
      result.updatedBudget_ = updatedBudget_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bron.grpc.updatedBudget) {
        return mergeFrom((com.bron.grpc.updatedBudget)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bron.grpc.updatedBudget other) {
      if (other == com.bron.grpc.updatedBudget.getDefaultInstance()) return this;
      if (!other.getYouHaveUpdated().isEmpty()) {
        youHaveUpdated_ = other.youHaveUpdated_;
        onChanged();
      }
      if (other.getUpdatedBudget() != 0) {
        setUpdatedBudget(other.getUpdatedBudget());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bron.grpc.updatedBudget parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bron.grpc.updatedBudget) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object youHaveUpdated_ = "";
    /**
     * <code>string youHaveUpdated = 1;</code>
     */
    public java.lang.String getYouHaveUpdated() {
      java.lang.Object ref = youHaveUpdated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        youHaveUpdated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string youHaveUpdated = 1;</code>
     */
    public com.google.protobuf.ByteString
        getYouHaveUpdatedBytes() {
      java.lang.Object ref = youHaveUpdated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        youHaveUpdated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string youHaveUpdated = 1;</code>
     */
    public Builder setYouHaveUpdated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      youHaveUpdated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string youHaveUpdated = 1;</code>
     */
    public Builder clearYouHaveUpdated() {
      
      youHaveUpdated_ = getDefaultInstance().getYouHaveUpdated();
      onChanged();
      return this;
    }
    /**
     * <code>string youHaveUpdated = 1;</code>
     */
    public Builder setYouHaveUpdatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      youHaveUpdated_ = value;
      onChanged();
      return this;
    }

    private int updatedBudget_ ;
    /**
     * <code>int32 updatedBudget = 2;</code>
     */
    public int getUpdatedBudget() {
      return updatedBudget_;
    }
    /**
     * <code>int32 updatedBudget = 2;</code>
     */
    public Builder setUpdatedBudget(int value) {
      
      updatedBudget_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 updatedBudget = 2;</code>
     */
    public Builder clearUpdatedBudget() {
      
      updatedBudget_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:updatedBudget)
  }

  // @@protoc_insertion_point(class_scope:updatedBudget)
  private static final com.bron.grpc.updatedBudget DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bron.grpc.updatedBudget();
  }

  public static com.bron.grpc.updatedBudget getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<updatedBudget>
      PARSER = new com.google.protobuf.AbstractParser<updatedBudget>() {
    @java.lang.Override
    public updatedBudget parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new updatedBudget(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<updatedBudget> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<updatedBudget> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bron.grpc.updatedBudget getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

